create table if not exists profiles (
  id bigint generated by default as identity primary key,
  user_id uuid unique not null references auth.users(id) on delete cascade,
  full_name text not null,
  email text not null,
  role text not null check (role in ('student','worker')),
  created_at timestamptz default now()
);

create table if not exists complaints (
  id bigint generated by default as identity primary key,
  student_id uuid not null references auth.users(id) on delete cascade,
  worker_id uuid references auth.users(id) on delete set null,
  title text not null,
  description text not null,
  category text not null,
  location text not null,
  priority text not null default 'Medium' check (priority in ('Low','Medium','High')),
  status text not null default 'Pending' check (status in ('Pending','Assigned','In Progress','Resolved','Rejected')),
  resolution_notes text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

alter table complaints add column if not exists resolution_notes text;

create table if not exists feedback (
  id bigint generated by default as identity primary key,
  complaint_id bigint unique not null references complaints(id) on delete cascade,
  student_id uuid not null references auth.users(id) on delete cascade,
  rating integer not null check (rating between 1 and 5),
  comment text,
  created_at timestamptz default now()
);

-- Input/business-rule constraints.
alter table profiles
  drop constraint if exists profiles_full_name_length;
alter table profiles
  add constraint profiles_full_name_length
  check (length(trim(full_name)) between 2 and 100);

alter table profiles
  drop constraint if exists profiles_email_length;
alter table profiles
  add constraint profiles_email_length
  check (length(trim(email)) between 3 and 320);

alter table complaints
  drop constraint if exists complaints_title_length;
alter table complaints
  add constraint complaints_title_length
  check (length(trim(title)) between 3 and 100);

alter table complaints
  drop constraint if exists complaints_description_length;
alter table complaints
  add constraint complaints_description_length
  check (length(trim(description)) between 10 and 2000);

alter table complaints
  drop constraint if exists complaints_category_length;
alter table complaints
  add constraint complaints_category_length
  check (length(trim(category)) between 2 and 50);

alter table complaints
  drop constraint if exists complaints_location_length;
alter table complaints
  add constraint complaints_location_length
  check (length(trim(location)) between 2 and 150);

alter table complaints
  drop constraint if exists complaints_resolution_notes_length;
alter table complaints
  add constraint complaints_resolution_notes_length
  check (resolution_notes is null or length(resolution_notes) <= 2000);

alter table feedback
  drop constraint if exists feedback_comment_length;
alter table feedback
  add constraint feedback_comment_length
  check (comment is null or length(comment) <= 1000);

-- Automatically provision every public signup as a student.
-- This avoids trusting a browser-side INSERT for profile creation and also
-- works when email confirmation is enabled (before the user has a session).
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  safe_name text;
begin
  safe_name := left(
    coalesce(
      nullif(trim(new.raw_user_meta_data ->> 'full_name'), ''),
      'HostelCare User'
    ),
    100
  );

  insert into public.profiles (user_id, full_name, email, role)
  values (new.id, safe_name, left(coalesce(new.email, ''), 320), 'student')
  on conflict (user_id) do nothing;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

revoke execute on function public.handle_new_user() from public;

alter table profiles enable row level security;
alter table complaints enable row level security;
alter table feedback enable row level security;

-- Prevent a signed-in user from changing their own role through the browser.
create or replace function public.prevent_self_role_change()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() = old.user_id and new.role is distinct from old.role then
    raise exception 'Profile role cannot be changed by the account owner';
  end if;
  return new;
end;
$$;

drop trigger if exists profiles_prevent_self_role_change on profiles;
create trigger profiles_prevent_self_role_change
before update on profiles
for each row execute function public.prevent_self_role_change();

revoke execute on function public.prevent_self_role_change() from public;

-- Cleanly recreate application policies.
drop policy if exists "profiles_select_own" on profiles;
drop policy if exists "profiles_insert_own" on profiles;
drop policy if exists "profiles_update_own" on profiles;
drop policy if exists "complaints_student_select" on complaints;
drop policy if exists "complaints_student_insert" on complaints;
drop policy if exists "complaints_worker_queue_select" on complaints;
drop policy if exists "feedback_student_select" on feedback;
drop policy if exists "feedback_student_insert" on feedback;

create policy "profiles_select_own"
on profiles for select to authenticated
using (auth.uid() = user_id);

-- IMPORTANT: browser self-registration can only create student profiles.
-- Worker profiles must be provisioned by a trusted/admin process.
create policy "profiles_insert_own"
on profiles for insert to authenticated
with check (
  auth.uid() = user_id
  and role = 'student'
);

create policy "profiles_update_own"
on profiles for update to authenticated
using (auth.uid() = user_id)
with check (
  auth.uid() = user_id
);

create policy "complaints_student_select"
on complaints for select to authenticated
using (
  auth.uid() = student_id
  and exists (
    select 1 from profiles p
    where p.user_id = auth.uid() and p.role = 'student'
  )
);

create policy "complaints_student_insert"
on complaints for insert to authenticated
with check (
  auth.uid() = student_id
  and exists (
    select 1 from profiles p
    where p.user_id = auth.uid() and p.role = 'student'
  )
);

-- Workers can see only:
--   * their own assigned complaints, OR
--   * the unassigned Pending queue.
create policy "complaints_worker_queue_select"
on complaints for select to authenticated
using (
  auth.uid() = worker_id
  or (
    worker_id is null
    and status = 'Pending'
    and exists (
      select 1 from profiles p
      where p.user_id = auth.uid() and p.role = 'worker'
    )
  )
);

-- No direct UPDATE policy is granted to workers. Status changes must use the
-- authorized update_complaint_status() RPC below.
create policy "feedback_student_select"
on feedback for select to authenticated
using (
  auth.uid() = student_id
  and exists (
    select 1 from complaints c
    where c.id = complaint_id
      and c.student_id = auth.uid()
  )
);

create policy "feedback_student_insert"
on feedback for insert to authenticated
with check (
  auth.uid() = student_id
  and exists (
    select 1 from profiles p
    where p.user_id = auth.uid() and p.role = 'student'
  )
  and exists (
    select 1 from complaints c
    where c.id = complaint_id
      and c.student_id = auth.uid()
      and c.status = 'Resolved'
  )
);

-- Atomic "Take Complaint" operation.
create or replace function public.take_complaint(p_complaint_id bigint)
returns complaints
language plpgsql
security definer
set search_path = public
as $$
declare
  result_row complaints;
begin
  if auth.uid() is null then
    raise exception 'Authentication required';
  end if;

  if not exists (
    select 1 from profiles
    where user_id = auth.uid() and role = 'worker'
  ) then
    raise exception 'Only workers can take complaints';
  end if;

  update complaints
  set worker_id = auth.uid(),
      status = 'Assigned',
      updated_at = now()
  where id = p_complaint_id
    and worker_id is null
    and status = 'Pending'
  returning * into result_row;

  if result_row.id is null then
    raise exception 'Complaint is already assigned or no longer pending';
  end if;

  return result_row;
end;
$$;

revoke execute on function public.take_complaint(bigint) from public;
grant execute on function public.take_complaint(bigint) to authenticated;

-- Secure worker status update.
-- Allowed transitions:
--   Assigned -> Assigned (edit notes)
--   Assigned -> In Progress
--   Assigned -> Rejected
--   In Progress -> In Progress (edit notes)
--   In Progress -> Resolved
--   In Progress -> Rejected
--   Resolved -> Resolved (edit notes)
--   Rejected -> Rejected (edit notes)
--
-- Pending is intentionally NOT editable here; it must first be claimed by
-- take_complaint(). This prevents a worker from changing an unassigned item.
create or replace function public.update_complaint_status(
  p_complaint_id bigint,
  p_status text,
  p_resolution_notes text default null
)
returns complaints
language plpgsql
security definer
set search_path = public
as $$
declare
  current_row complaints;
  result_row complaints;
begin
  if auth.uid() is null then
    raise exception 'Authentication required';
  end if;

  if not exists (
    select 1 from profiles
    where user_id = auth.uid() and role = 'worker'
  ) then
    raise exception 'Only workers can update complaints';
  end if;

  if p_status not in ('Assigned', 'In Progress', 'Resolved', 'Rejected') then
    raise exception 'Invalid complaint status';
  end if;

  if p_resolution_notes is not null and length(p_resolution_notes) > 2000 then
    raise exception 'Resolution notes must be 2000 characters or less';
  end if;

  select * into current_row
  from complaints
  where id = p_complaint_id
    and worker_id = auth.uid()
  for update;

  if current_row.id is null then
    raise exception 'Complaint is not assigned to this worker';
  end if;

  if current_row.status <> p_status then
    if not (
      (current_row.status = 'Assigned' and p_status in ('In Progress', 'Rejected'))
      or
      (current_row.status = 'In Progress' and p_status in ('Resolved', 'Rejected'))
    ) then
      raise exception 'Invalid status transition from % to %', current_row.status, p_status;
    end if;
  end if;

  update complaints
  set status = p_status,
      resolution_notes = nullif(trim(p_resolution_notes), ''),
      updated_at = now()
  where id = p_complaint_id
    and worker_id = auth.uid()
  returning * into result_row;

  return result_row;
end;
$$;

revoke execute on function public.update_complaint_status(bigint, text, text) from public;
grant execute on function public.update_complaint_status(bigint, text, text) to authenticated;

create index if not exists complaints_student_idx on complaints(student_id);
create index if not exists complaints_worker_idx on complaints(worker_id);
create index if not exists complaints_status_idx on complaints(status);
create index if not exists complaints_created_idx on complaints(created_at desc);
create index if not exists feedback_student_idx on feedback(student_id);
